excluded:
  - Pods
  - FirebaseStarterSwiftUIAppTests
  - FirebaseStarterSwiftUIAppUITests

opt_in_rules:
  - empty_count
  - empty_string
  - closure_spacing
  - explicit_init
  - first_where
  - modifier_order
  - nimble_operator
  - operator_usage_whitespace
  - overridden_super_call
  - private_outlet
  - prohibited_super_call
  - quick_discouraged_call
  - redundant_nil_coalescing
  - single_test_class
  - sorted_imports
  - switch_case_on_newline
  - unneeded_parentheses_in_closure_argument
  - vertical_parameter_alignment_on_call
  - weak_delegate

line_length:
  warning: 120
  error: 200

identifier_name:
  min_length: 2

type_name:
  min_length: 3

function_parameter_count:
  warning: 6
  error: 8

file_length:
  warning: 400
  error: 600

cyclomatic_complexity:
  warning: 10
  error: 20

reporter: "xcode"
