# Uncomment the next line to define a global platform for your project
platform :ios, '15.0'

target 'FirebaseStarterSwiftUIApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FirebaseStarterSwiftUIApp
  pod 'Firebase/Auth', '9.6.0'
  pod 'FBSDKCoreKit', '~> 14.1.0'
  pod 'FBSDKLoginKit', '~> 14.1.0'
  pod 'SwiftLint', '~> 0.52.0'
end
